use crate::escaping::escape_ts;
use surfacer_ir::{
    resolve_auth, AuthMode, CredentialLocation, OAuth2Grant, OperationKind, OperationTransport,
    SecretRef, SiteDescriptor,
};

/// Emit a standalone MCP server for a descriptor.
///
/// The just-bash target hands tools to one runtime. This one speaks the
/// protocol directly, so any MCP client reaches the same surface without that
/// runtime in between.
///
/// Every tool declares its parameters, so a client sees what a command takes
/// before calling it rather than discovering it from an error.
///
/// Auth (AE-V5): each tool resolves its operation's auth and attaches a token
/// before the fetch, mirroring the ts-cli runtime. The one shape difference is
/// failure: a CLI exits non-zero, but an MCP tool cannot. So a missing or
/// expired browser-bootstrapped token becomes a tool error (`isError: true`)
/// carrying the `surfacer auth login <site>` hint, never a process exit and
/// never a browser attempt inside the server.
pub fn emit_mcp_server(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = escape_ts(&descriptor.meta.display_name);
    let source_url = &descriptor.meta.source_url;
    let base = base_url(source_url);

    let mut tools = Vec::new();
    let mut auth_entries = Vec::new();
    let names = surfacer_ir::unique_command_names(descriptor);

    for (op, unique_name) in descriptor.operations.iter().zip(&names) {
        let name = unique_name.replace(' ', "_");
        let kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let endpoint = match &op.transport {
            OperationTransport::Http(http) => descriptor
                .http
                .as_ref()
                .and_then(|surface| surface.endpoints.get(http.endpoint_index)),
            OperationTransport::Ax(_) => None,
        };

        let path = endpoint
            .map(|e| e.path.split('?').next().unwrap_or(&e.path).to_string())
            .unwrap_or_else(|| format!("/{}", op.command_path.join("/")));

        let params = endpoint.map(|e| e.params.as_slice()).unwrap_or_default();

        let schema = if params.is_empty() {
            "z.object({})".to_string()
        } else {
            let fields = params
                .iter()
                .map(|p| {
                    let described = match &p.example {
                        Some(example) => {
                            format!(r#".describe("observed value: {}")"#, escape_ts(example))
                        }
                        None => String::new(),
                    };
                    // Recon cannot tell an optional parameter from one that
                    // simply appeared in every captured request.
                    format!(
                        "      {}: z.string().optional(){},",
                        quote_key(&p.name),
                        described
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!("z.object({{\n{fields}\n    }})")
        };

        let description = if restates(unique_name, &op.description) {
            format!("{} on {}", kind, escape_ts(&path))
        } else {
            escape_ts(&op.description)
        };

        // Resolve the operation's auth and, when it is not None, emit an entry
        // in the AUTH map keyed by the tool name. `call` looks it up and runs
        // `resolveToken` before the fetch. A None (or absent) auth leaves no
        // entry, so a public descriptor emits an empty AUTH map and no token
        // path is ever baked in.
        if let Some(record) = auth_record(resolve_auth(op, descriptor.http.as_ref()), site) {
            auth_entries.push(format!("  {}: {record},", quote_key(&name)));
        }

        tools.push(format!(
            r#"  server.registerTool(
    "{name}",
    {{
      description: "{description}",
      inputSchema: {schema},
      annotations: {{ readOnlyHint: {read_only} }},
    }},
    async (args) => call("{name}", "{kind}", "{path}", args),
  );"#,
            read_only = matches!(op.operation_kind, OperationKind::Read),
        ));
    }

    let registrations = tools.join("\n\n");
    let auth_map = if auth_entries.is_empty() {
        "const AUTH = {};".to_string()
    } else {
        format!("const AUTH = {{\n{}\n}};", auth_entries.join("\n"))
    };

    format!(
        r#"// Auto-generated by surfacer emit mcp
// Source: {source_url}
// Site: {site} ({display})
//
// Run it:
//   npm install @modelcontextprotocol/server zod
//   node {site}.mcp.js
//
// Register it with a client, for example in Claude Code:
//   claude mcp add {site} -- node /absolute/path/to/{site}.mcp.js

import {{ McpServer }} from "@modelcontextprotocol/server";
import {{ serveStdio }} from "@modelcontextprotocol/server/stdio";
import {{ readFileSync }} from "node:fs";
import {{ homedir }} from "node:os";
import * as z from "zod/v4";

const BASE = "{base}";

/**
 * Per-tool auth records, keyed by tool name. A tool with no entry runs
 * unauthenticated (an explicit or defaulted AuthMode::None). The token path for
 * browser-bootstrapped tools is baked in at emit time because this server has
 * no access to the Rust config helpers.
 */
{auth_map}

/**
 * Operation kinds allowed to run without an explicit opt-in.
 *
 * Recon cannot tell a harmless write from a destructive one, so writes stay
 * blocked until a human widens this. Auth is orthogonal: attaching a token
 * never widens what kind of operation a tool will run.
 */
const ALLOWED_KINDS = new Set(["read"]);

/** A tool error carrying a plain-text message. MCP tools cannot exit. */
function toolError(text) {{
  return {{ isError: true, content: [{{ type: "text", text }}] }};
}}

function withQuery(url, args) {{
  if (!args || typeof args !== "object") return url;
  const entries = Object.entries(args).filter(
    ([, value]) => value !== undefined && value !== null && value !== "",
  );
  if (entries.length === 0) return url;
  const target = new URL(url);
  for (const [key, value] of entries) {{
    target.searchParams.set(key, String(value));
  }}
  return target.toString();
}}

/** Decode a JWT `exp` (epoch seconds) without a library. */
function decodeExp(jwt) {{
  const part = jwt.split(".")[1];
  if (!part) throw new Error("token is not a JWT");
  const padded = part + "=".repeat((4 - (part.length % 4)) % 4);
  const claims = JSON.parse(Buffer.from(padded, "base64url").toString());
  if (typeof claims.exp !== "number") throw new Error("token has no exp claim");
  return claims.exp;
}}

function readSecret(ref) {{
  if (ref.from === "env") {{
    const value = process.env[ref.var];
    if (!value) throw new Error(`missing env var ${{ref.var}}`);
    return value;
  }}
  if (ref.from === "file") {{
    return readFileSync(ref.path, "utf-8").trim();
  }}
  throw new Error(`cannot read an ${{ref.from}} secret without an acquisition step`);
}}

// In-process OAuth2 token cache, keyed by token URL. Mirrors the ts-cli
// runtime: acquire once, reuse until 60s before the TTL elapses.
const oauthCache = new Map();

async function resolveOAuth2(auth) {{
  const cached = oauthCache.get(auth.tokenUrl);
  const now = Math.floor(Date.now() / 1000);
  if (cached && cached.expiresAt > now + 60) return cached.token;

  const creds = readSecret(auth.credentials);
  const form = new URLSearchParams();
  form.set("grant_type", auth.grant === "clientCredentials" ? "client_credentials" : "password");
  if (auth.scopes && auth.scopes.length > 0) form.set("scope", auth.scopes.join(" "));
  const response = await fetch(auth.tokenUrl, {{
    method: "POST",
    headers: {{
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: creds,
    }},
    body: form.toString(),
  }});
  if (!response.ok) {{
    throw new Error(`token endpoint returned ${{response.status}}`);
  }}
  const data = await response.json();
  const token = data.access_token;
  if (!token) throw new Error("token endpoint returned no access_token");
  const lifetime = auth.ttl ? auth.ttl.seconds : data.expires_in || 3600;
  oauthCache.set(auth.tokenUrl, {{ token, expiresAt: now + lifetime }});
  return token;
}}

/**
 * Resolve the token for an auth record. Returns `{{ token }}` on success or
 * `{{ error }}` with a reauth hint the caller turns into a tool error. Never
 * opens a browser: a browser-bootstrapped token is minted by
 * `surfacer auth login` in a separate process, then replayed here headless.
 */
async function resolveToken(auth) {{
  if (auth.mode === "apiKey") {{
    return {{ token: readSecret(auth.secret) }};
  }}
  if (auth.mode === "oAuth2") {{
    return {{ token: await resolveOAuth2(auth) }};
  }}
  if (auth.mode === "browserToken") {{
    let cache;
    try {{
      cache = JSON.parse(readFileSync(auth.tokenPath, "utf-8"));
    }} catch {{
      return {{
        error: `no captured token at ${{auth.tokenPath}}. run \`surfacer auth login {site}\` then retry`,
      }};
    }}
    const now = Math.floor(Date.now() / 1000);
    if (typeof cache.expiresAt === "number" && cache.expiresAt <= now + 60) {{
      return {{
        error: `captured token at ${{auth.tokenPath}} has expired. run \`surfacer auth login {site}\` then retry`,
      }};
    }}
    return {{ token: cache.token }};
  }}
  return {{ error: `unknown auth mode: ${{auth.mode}}` }};
}}

/** Attach a resolved token to the request per a TokenUse (header or query). */
function attachToken(url, headers, use, token) {{
  const value = (use.valuePrefix || "") + token;
  if (use.location === "query") {{
    const target = new URL(url);
    target.searchParams.set(use.name, value);
    return target.toString();
  }}
  headers[use.name] = value;
  return url;
}}

async function call(name, kind, path, args) {{
  if (!ALLOWED_KINDS.has(kind)) {{
    return toolError(
      `blocked: ${{name}} is a ${{kind}} operation. Add "${{kind}}" to ALLOWED_KINDS to permit it.`,
    );
  }}

  let url = withQuery(BASE + path, args);
  const headers = {{}};

  const auth = AUTH[name];
  if (auth) {{
    let resolved;
    try {{
      resolved = await resolveToken(auth);
    }} catch (err) {{
      return toolError(`auth failed for ${{name}}: ${{err.message}}`);
    }}
    if (resolved.error) {{
      return toolError(resolved.error);
    }}
    url = attachToken(url, headers, auth.use, resolved.token);
  }}

  const response = await fetch(url, {{ headers }});
  const body = await response.text();

  return {{
    content: [{{ type: "text", text: body }}],
    structuredContent: {{ status: response.status, url }},
    isError: !response.ok,
  }};
}}

serveStdio(() => {{
  const server = new McpServer({{ name: "{site}", version: "{version}" }});

{registrations}

  return server;
}});
"#,
        version = descriptor.meta.ir_version,
    )
}

/// Build the JS auth record literal for a resolved `AuthMode`, or `None` when
/// the operation is unauthenticated (so it emits no AUTH entry at all).
///
/// The record carries only what the emitted runtime reads: the mode tag, the
/// `use` shape (how to attach the token), and the mode-specific inputs. The
/// browser-bootstrapped path is baked in here because the standalone JS has no
/// Rust config helper to compute it.
fn auth_record(auth: Option<&AuthMode>, site: &str) -> Option<String> {
    match auth {
        None | Some(AuthMode::None) => None,
        Some(AuthMode::ApiKey(api)) => {
            // ApiKey attaches the raw secret via its own location/name, so the
            // `use` shape mirrors the ApiKeyAuth fields.
            let use_ = token_use_literal(&api.location, &api.name, api.value_prefix.as_deref());
            let secret = secret_ref_literal(&api.secret_ref);
            Some(format!(
                r#"{{ mode: "apiKey", use: {use_}, secret: {secret} }}"#
            ))
        }
        Some(AuthMode::OAuth2(oauth)) => {
            // OAuth2 defaults to `Authorization: Bearer <token>` when no
            // token_use is given, matching the IR doc's stated default.
            let use_ = match &oauth.token_use {
                Some(tu) => {
                    token_use_literal(&tu.location, &tu.name, tu.value_prefix.as_deref())
                }
                None => token_use_literal(&CredentialLocation::Header, "Authorization", Some("Bearer ")),
            };
            let grant = match oauth.grant {
                OAuth2Grant::ClientCredentials => "clientCredentials",
                _ => "password",
            };
            let scopes = if oauth.scopes.is_empty() {
                "[]".to_string()
            } else {
                let items = oauth
                    .scopes
                    .iter()
                    .map(|s| format!(r#""{}""#, escape_ts(s)))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("[{items}]")
            };
            let ttl = match &oauth.ttl {
                Some(t) => format!("{{ seconds: {} }}", t.seconds),
                None => "null".to_string(),
            };
            let creds = secret_ref_literal(&oauth.credentials);
            Some(format!(
                r#"{{ mode: "oAuth2", use: {use_}, tokenUrl: "{}", grant: "{grant}", scopes: {scopes}, credentials: {creds}, ttl: {ttl} }}"#,
                escape_ts(&oauth.token_url),
            ))
        }
        Some(AuthMode::BrowserBootstrappedToken(browser)) => {
            let use_ = token_use_literal(
                &browser.use_.location,
                &browser.use_.name,
                browser.use_.value_prefix.as_deref(),
            );
            // Bake the token path per the cross-language contract:
            // $HOME/.surfacer/sites/<site>/token.json, computed at runtime from
            // homedir() so it survives a different HOME than emit time.
            let token_path =
                format!(r#"join(homedir(), ".surfacer", "sites", "{}", "token.json")"#, escape_ts(site));
            let _ = &browser.ttl; // TTL is enforced by expiresAt in the token file.
            Some(format!(
                r#"{{ mode: "browserToken", use: {use_}, tokenPath: {token_path} }}"#
            ))
        }
    }
}

/// Render a `TokenUse`-shaped JS object literal: `{{ location, name, valuePrefix }}`.
fn token_use_literal(location: &CredentialLocation, name: &str, value_prefix: Option<&str>) -> String {
    let loc = match location {
        CredentialLocation::Header => "header",
        CredentialLocation::Query => "query",
    };
    let prefix = match value_prefix {
        Some(p) => format!(r#""{}""#, escape_ts(p)),
        None => "\"\"".to_string(),
    };
    format!(
        r#"{{ location: "{loc}", name: "{}", valuePrefix: {prefix} }}"#,
        escape_ts(name)
    )
}

/// Render a `SecretRef` JS literal the emitted `readSecret` understands.
/// An `Acquired` source has no static location; the runtime rejects it, so the
/// literal preserves that so the failure is honest rather than silent.
fn secret_ref_literal(secret: &SecretRef) -> String {
    match secret {
        SecretRef::Env { var } => format!(r#"{{ from: "env", var: "{}" }}"#, escape_ts(var)),
        SecretRef::File { path } => format!(r#"{{ from: "file", path: "{}" }}"#, escape_ts(path)),
        SecretRef::Acquired => r#"{ from: "acquired" }"#.to_string(),
    }
}

/// Quote a key only when it is not a bare identifier, so the common case stays
/// readable.
fn quote_key(name: &str) -> String {
    let bare = !name.is_empty()
        && name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if bare {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts(name))
    }
}

/// Recon derives command names and descriptions from the same path, so a
/// description often restates the command and tells a client nothing.
fn restates(command: &str, description: &str) -> bool {
    fn squash(value: &str) -> String {
        value
            .chars()
            .filter(|c| c.is_alphanumeric())
            .flat_map(char::to_lowercase)
            .collect()
    }
    description.trim().is_empty() || squash(command) == squash(description)
}


fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.trim_end_matches('/').to_string())
}
