use surfacer_ir::{OperationKind, OperationTransport, SiteDescriptor};

/// Emit a standalone MCP server for a descriptor.
///
/// The just-bash target hands tools to one runtime. This one speaks the
/// protocol directly, so any MCP client reaches the same surface without that
/// runtime in between.
///
/// Every tool declares its parameters, so a client sees what a command takes
/// before calling it rather than discovering it from an error.
pub fn emit_mcp_server(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = escape_ts(&descriptor.meta.display_name);
    let source_url = &descriptor.meta.source_url;
    let base = base_url(source_url);

    let mut tools = Vec::new();
    let names = surfacer_ir::unique_command_names(descriptor);

    for (op, unique_name) in descriptor.operations.iter().zip(&names) {
        let name = unique_name.replace(' ', "_");
        let kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let endpoint = match &op.transport {
            OperationTransport::Http(http) => descriptor
                .http
                .as_ref()
                .and_then(|surface| surface.endpoints.get(http.endpoint_index)),
            OperationTransport::Ax(_) => None,
        };

        let path = endpoint
            .map(|e| e.path.split('?').next().unwrap_or(&e.path).to_string())
            .unwrap_or_else(|| format!("/{}", op.command_path.join("/")));

        let params = endpoint.map(|e| e.params.as_slice()).unwrap_or_default();

        let schema = if params.is_empty() {
            "z.object({})".to_string()
        } else {
            let fields = params
                .iter()
                .map(|p| {
                    let described = match &p.example {
                        Some(example) => format!(
                            r#".describe("observed value: {}")"#,
                            escape_ts(example)
                        ),
                        None => String::new(),
                    };
                    // Recon cannot tell an optional parameter from one that
                    // simply appeared in every captured request.
                    format!(
                        "      {}: z.string().optional(){},",
                        quote_key(&p.name),
                        described
                    )
                })
                .collect::<Vec<_>>()
                .join("\n");
            format!("z.object({{\n{fields}\n    }})")
        };

        let description = if restates(unique_name, &op.description) {
            format!("{} on {}", kind, escape_ts(&path))
        } else {
            escape_ts(&op.description)
        };

        tools.push(format!(
            r#"  server.registerTool(
    "{name}",
    {{
      description: "{description}",
      inputSchema: {schema},
      annotations: {{ readOnlyHint: {read_only} }},
    }},
    async (args) => call("{name}", "{kind}", "{path}", args),
  );"#,
            read_only = matches!(op.operation_kind, OperationKind::Read),
        ));
    }

    let registrations = tools.join("\n\n");

    format!(
        r#"// Auto-generated by surfacer emit mcp
// Source: {source_url}
// Site: {site} ({display})
//
// Run it:
//   npm install @modelcontextprotocol/server zod
//   node {site}.mcp.js
//
// Register it with a client, for example in Claude Code:
//   claude mcp add {site} -- node /absolute/path/to/{site}.mcp.js

import {{ McpServer }} from "@modelcontextprotocol/server";
import {{ serveStdio }} from "@modelcontextprotocol/server/stdio";
import * as z from "zod/v4";

const BASE = "{base}";

/**
 * Operation kinds allowed to run without an explicit opt-in.
 *
 * Recon cannot tell a harmless write from a destructive one, so writes stay
 * blocked until a human widens this.
 */
const ALLOWED_KINDS = new Set(["read"]);

function withQuery(url, args) {{
  if (!args || typeof args !== "object") return url;
  const entries = Object.entries(args).filter(
    ([, value]) => value !== undefined && value !== null && value !== "",
  );
  if (entries.length === 0) return url;
  const target = new URL(url);
  for (const [key, value] of entries) {{
    target.searchParams.set(key, String(value));
  }}
  return target.toString();
}}

async function call(name, kind, path, args) {{
  if (!ALLOWED_KINDS.has(kind)) {{
    return {{
      isError: true,
      content: [
        {{
          type: "text",
          text: `blocked: ${{name}} is a ${{kind}} operation. Add "${{kind}}" to ALLOWED_KINDS to permit it.`,
        }},
      ],
    }};
  }}

  const url = withQuery(BASE + path, args);
  const response = await fetch(url);
  const body = await response.text();

  return {{
    content: [{{ type: "text", text: body }}],
    structuredContent: {{ status: response.status, url }},
    isError: !response.ok,
  }};
}}

serveStdio(() => {{
  const server = new McpServer({{ name: "{site}", version: "{version}" }});

{registrations}

  return server;
}});
"#,
        version = descriptor.meta.ir_version,
    )
}

/// Quote a key only when it is not a bare identifier, so the common case stays
/// readable.
fn quote_key(name: &str) -> String {
    let bare = !name.is_empty()
        && name
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if bare {
        name.to_string()
    } else {
        format!("\"{}\"", escape_ts(name))
    }
}

/// Recon derives command names and descriptions from the same path, so a
/// description often restates the command and tells a client nothing.
fn restates(command: &str, description: &str) -> bool {
    fn squash(value: &str) -> String {
        value
            .chars()
            .filter(|c| c.is_alphanumeric())
            .flat_map(char::to_lowercase)
            .collect()
    }
    description.trim().is_empty() || squash(command) == squash(description)
}

fn escape_ts(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', " ")
        .replace('\r', " ")
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.trim_end_matches('/').to_string())
}
