use serde_json::{json, Map, Value};
use surfacer_ir::{
    HttpMethod, OperationKind, OperationTransport, SiteDescriptor,
};

/// Emit an OpenAPI 3.1 document for a descriptor.
///
/// This target exists to reach tools nobody here has to write an emitter for.
/// A spec feeds SDK generators, HTTP clients, and API consoles, so one emitter
/// buys every consumer that already speaks OpenAPI.
///
/// Recon observes traffic rather than reading documentation, so the document
/// says only what was seen. Response schemas are absent because recon captured
/// bodies, not contracts, and inventing one would make the spec look more
/// authoritative than the evidence behind it.
pub fn emit_openapi(descriptor: &SiteDescriptor) -> String {
    let mut paths = Map::new();
    let names = surfacer_ir::unique_command_names(descriptor);

    for (op, unique_name) in descriptor.operations.iter().zip(&names) {
        let OperationTransport::Http(http) = &op.transport else {
            // Accessibility-tree operations have no URL to describe.
            continue;
        };

        let Some(endpoint) = descriptor
            .http
            .as_ref()
            .and_then(|surface| surface.endpoints.get(http.endpoint_index))
        else {
            continue;
        };

        let path = endpoint
            .path
            .split('?')
            .next()
            .unwrap_or(&endpoint.path)
            .to_string();

        let parameters: Vec<Value> = endpoint
            .params
            .iter()
            .map(|param| {
                let mut schema = Map::new();
                schema.insert("type".into(), json!("string"));
                if let Some(example) = &param.example {
                    schema.insert("example".into(), json!(example));
                }
                json!({
                    "name": param.name,
                    "in": "query",
                    // Recon cannot tell an optional parameter from one that
                    // simply appeared in every captured request.
                    "required": false,
                    "schema": Value::Object(schema),
                })
            })
            .collect();

        let mut operation = Map::new();
        operation.insert("operationId".into(), json!(unique_name.replace(' ', "_")));
        operation.insert("summary".into(), json!(op.summary));
        if !describes_the_same_thing(unique_name, &op.description) {
            operation.insert("description".into(), json!(op.description));
        }
        operation.insert("tags".into(), json!([tag_for(&op.command_path)]));
        if !parameters.is_empty() {
            operation.insert("parameters".into(), Value::Array(parameters));
        }
        operation.insert(
            "responses".into(),
            json!({
                "default": {
                    "description": response_description(endpoint.sample_response_content_type.as_deref()),
                }
            }),
        );
        operation.insert(
            "x-surfacer-operation-kind".into(),
            json!(kind_name(&op.operation_kind)),
        );

        let entry = paths
            .entry(path)
            .or_insert_with(|| Value::Object(Map::new()));
        if let Some(item) = entry.as_object_mut() {
            item.insert(method_name(&endpoint.method).into(), Value::Object(operation));
        }
    }

    let document = json!({
        "openapi": "3.1.0",
        "info": {
            "title": descriptor.meta.display_name,
            "version": descriptor.meta.ir_version,
            "description": format!(
                "Generated by surfacer from an observed surface. Operations and \
                 parameters reflect traffic captured during recon, not published \
                 documentation. Source: {}",
                descriptor.meta.source_url
            ),
        },
        "servers": [{ "url": base_url(&descriptor.meta.source_url) }],
        "paths": Value::Object(paths),
    });

    serde_json::to_string_pretty(&document).unwrap_or_else(|_| "{}".to_string())
}

/// Group operations by their first path segment so consumers get a usable
/// namespace instead of one flat list.
fn tag_for(command_path: &[String]) -> String {
    command_path
        .first()
        .cloned()
        .unwrap_or_else(|| "default".to_string())
}

fn response_description(content_type: Option<&str>) -> String {
    match content_type {
        Some(ct) => format!("Observed during recon, content type {ct}"),
        None => "Observed during recon".to_string(),
    }
}

fn kind_name(kind: &OperationKind) -> &'static str {
    match kind {
        OperationKind::Read => "read",
        OperationKind::Write => "write",
        OperationKind::Other => "other",
    }
}

fn method_name(method: &HttpMethod) -> &'static str {
    match method {
        HttpMethod::Get => "get",
        HttpMethod::Post => "post",
        HttpMethod::Put => "put",
        HttpMethod::Patch => "patch",
        HttpMethod::Delete => "delete",
        HttpMethod::Head => "head",
        HttpMethod::Options => "options",
    }
}

/// Recon derives command names and descriptions from the same path, so a
/// description often restates the command. Repeating it in the spec adds noise
/// for every downstream generator.
fn describes_the_same_thing(command: &str, description: &str) -> bool {
    fn squash(value: &str) -> String {
        value
            .chars()
            .filter(|c| c.is_alphanumeric())
            .flat_map(char::to_lowercase)
            .collect()
    }
    description.trim().is_empty() || squash(command) == squash(description)
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.trim_end_matches('/').to_string())
}
