import {
  endpointFor,
  type OperationDescriptor,
  paramsFor,
  type SiteDescriptor,
} from "./types";

/**
 * Preview versions of the emitters that ship in the CLI. They exist so the
 * site shows what an IR turns into without asking you to install anything.
 *
 * The CLI remains authoritative: these render a readable approximation, not
 * the byte-identical artifact.
 */

function bareUrl(descriptor: SiteDescriptor, op: OperationDescriptor): string {
  const endpoint = endpointFor(descriptor, op);
  const source = descriptor.meta.sourceUrl;
  let base: string;
  try {
    const parsed = new URL(source);
    base = `${parsed.protocol}//${parsed.host}`;
  } catch {
    base = source;
  }
  const path = endpoint?.path.split("?")[0] ?? `/${op.commandPath.join("/")}`;
  return base + path;
}

/**
 * True when a description carries no information the command name lacks.
 *
 * Recon derives both from the same path, so `index-html` becomes the command
 * and `index html` becomes its description. Comparing them with separators
 * removed catches every variant of that.
 */
function addsNothing(command: string, description: string): boolean {
  const squash = (value: string) =>
    value.replace(/[^a-z0-9]/gi, "").toLowerCase();
  return description.trim() === "" || squash(command) === squash(description);
}

export function emitHelp(descriptor: SiteDescriptor): string {
  const width = Math.max(
    ...descriptor.operations.map((op) => op.commandPath.join(" ").length),
    0,
  );
  const lines: string[] = [
    `${descriptor.meta.siteName} - ${descriptor.meta.displayName}`,
    "",
    "USAGE",
    `  ${descriptor.meta.siteName} <command> [key=value ...]`,
    "",
    "COMMANDS",
  ];

  for (const op of descriptor.operations) {
    const name = op.commandPath.join(" ");
    const description = addsNothing(name, op.description) ? "" : op.description;
    lines.push(`  ${name.padEnd(width)}  ${description}`.trimEnd());
    const params = paramsFor(descriptor, op);
    if (params.length > 0) {
      const flags = params
        .map((p) => (p.example ? `${p.name}=${p.example}` : `${p.name}=`))
        .join(" ");
      lines.push(`  ${"".padEnd(width)}  ${flags}`);
    }
  }

  lines.push(
    "",
    "FLAGS",
    "  --json    Print the raw response body",
    "  --help    Show this help",
  );
  return lines.join("\n");
}

export function emitTsCli(descriptor: SiteDescriptor): string {
  const ops = descriptor.operations
    .map((op) => {
      const params = paramsFor(descriptor, op)
        .map((p) => `{ name: "${p.name}", example: "${p.example ?? ""}" }`)
        .join(", ");
      const path = bareUrl(descriptor, op).replace(/^https?:\/\/[^/]+/, "");
      return `  {
    name: "${op.commandPath.join(" ")}",
    description: "${op.description}",
    kind: "${op.operationKind}",
    path: "${path}",
    params: [${params}],
  }`;
    })
    .join(",\n");

  return `// Auto-generated by surfacer emit ts-cli
// Source: ${descriptor.meta.sourceUrl}
//
// Build a native binary (no runtime required):
//   scriptc build ${descriptor.meta.siteName}.ts --dynamic -o ${descriptor.meta.siteName}

const OPERATIONS: Operation[] = [
${ops}
];

// Recon cannot tell a harmless write from a destructive one, so writes stay
// blocked until a human widens this.
const ALLOWED_KINDS = new Set<string>(["read"]);
`;
}

export function emitJustBash(descriptor: SiteDescriptor): string {
  const site = descriptor.meta.siteName;
  const tools = descriptor.operations
    .map((op) => {
      const name = op.commandPath.join(".");
      const params = paramsFor(descriptor, op);
      const doc =
        params.length > 0
          ? `\n      // Parameters observed during recon:\n${params
              .map(
                (p) =>
                  `      //   ${p.name}${p.example ? ` (e.g. ${p.example})` : ""}`,
              )
              .join("\n")}\n`
          : "";
      return `    "${site}.${name}": {
      description: "${op.description}",${doc}
      execute: async (args) => {
        assertAllowed("${site}.${name}", "${op.operationKind}");
        const url = withQuery("${bareUrl(descriptor, op)}", args);
        const res = await fetch(url);
        return { status: res.status, url, body: await res.text() };
      },
    }`;
    })
    .join(",\n");

  return `// Auto-generated by surfacer emit just-bash
// Source: ${descriptor.meta.sourceUrl}

export const surfacerTools = {
${tools}
};
`;
}

export const TARGETS = [
  { id: "help", label: "help", lang: "clihelp", emit: emitHelp },
  { id: "ts-cli", label: "ts-cli", lang: "ts", emit: emitTsCli },
  { id: "just-bash", label: "just-bash", lang: "js", emit: emitJustBash },
] as const;

export type TargetId = (typeof TARGETS)[number]["id"];
