import {
  type AuthMode,
  endpointFor,
  type OperationDescriptor,
  paramsFor,
  resolveAuth,
  type SiteDescriptor,
} from "./types";

/**
 * Preview versions of the emitters that ship in the CLI. They exist so the
 * site shows what an IR turns into without asking you to install anything.
 *
 * The CLI remains authoritative: these render a readable approximation, not
 * the byte-identical artifact.
 */

function bareUrl(descriptor: SiteDescriptor, op: OperationDescriptor): string {
  const endpoint = endpointFor(descriptor, op);
  const source = descriptor.meta.sourceUrl;
  let base: string;
  try {
    const parsed = new URL(source);
    base = `${parsed.protocol}//${parsed.host}`;
  } catch {
    base = source;
  }
  const path = endpoint?.path.split("?")[0] ?? `/${op.commandPath.join("/")}`;
  return base + path;
}

/**
 * True when a description carries no information the command name lacks.
 *
 * Recon derives both from the same path, so `index-html` becomes the command
 * and `index html` becomes its description. Comparing them with separators
 * removed catches every variant of that.
 */
function addsNothing(command: string, description: string): boolean {
  const squash = (value: string) =>
    value.replace(/[^a-z0-9]/gi, "").toLowerCase();
  return description.trim() === "" || squash(command) === squash(description);
}

export function emitHelp(descriptor: SiteDescriptor): string {
  const width = Math.max(
    ...descriptor.operations.map((op) => op.commandPath.join(" ").length),
    0,
  );
  const lines: string[] = [
    `${descriptor.meta.siteName} - ${descriptor.meta.displayName}`,
    "",
    "USAGE",
    `  ${descriptor.meta.siteName} <command> [key=value ...]`,
    "",
    "COMMANDS",
  ];

  for (const op of descriptor.operations) {
    const name = op.commandPath.join(" ");
    const description = addsNothing(name, op.description) ? "" : op.description;
    lines.push(`  ${name.padEnd(width)}  ${description}`.trimEnd());
    const params = paramsFor(descriptor, op);
    if (params.length > 0) {
      const flags = params
        .map((p) => (p.example ? `${p.name}=${p.example}` : `${p.name}=`))
        .join(" ");
      lines.push(`  ${"".padEnd(width)}  ${flags}`);
    }
  }

  lines.push(
    "",
    "FLAGS",
    "  --json    Print the raw response body",
    "  --help    Show this help",
  );
  return lines.join("\n");
}

export function emitTsCli(descriptor: SiteDescriptor): string {
  const ops = descriptor.operations
    .map((op) => {
      const params = paramsFor(descriptor, op)
        .map((p) => `{ name: "${p.name}", example: "${p.example ?? ""}" }`)
        .join(", ");
      const path = bareUrl(descriptor, op).replace(/^https?:\/\/[^/]+/, "");
      return `  {
    name: "${op.commandPath.join(" ")}",
    description: "${op.description}",
    kind: "${op.operationKind}",
    path: "${path}",
    params: [${params}],
  }`;
    })
    .join(",\n");

  return `// Auto-generated by surfacer emit ts-cli
// Source: ${descriptor.meta.sourceUrl}
//
// Build a native binary (no runtime required):
//   scriptc build ${descriptor.meta.siteName}.ts --dynamic -o ${descriptor.meta.siteName}

const OPERATIONS: Operation[] = [
${ops}
];

// Recon cannot tell a harmless write from a destructive one, so writes stay
// blocked until a human widens this.
const ALLOWED_KINDS = new Set<string>(["read"]);
`;
}

export function emitJustBash(descriptor: SiteDescriptor): string {
  const site = descriptor.meta.siteName;
  const tools = descriptor.operations
    .map((op) => {
      const name = op.commandPath.join(".");
      const params = paramsFor(descriptor, op);
      const doc =
        params.length > 0
          ? `\n      // Parameters observed during recon:\n${params
              .map(
                (p) =>
                  `      //   ${p.name}${p.example ? ` (e.g. ${p.example})` : ""}`,
              )
              .join("\n")}\n`
          : "";
      return `    "${site}.${name}": {
      description: "${op.description}",${doc}
      execute: async (args) => {
        assertAllowed("${site}.${name}", "${op.operationKind}");
        const url = withQuery("${bareUrl(descriptor, op)}", args);
        const res = await fetch(url);
        return { status: res.status, url, body: await res.text() };
      },
    }`;
    })
    .join(",\n");

  return `// Auto-generated by surfacer emit just-bash
// Source: ${descriptor.meta.sourceUrl}

export const surfacerTools = {
${tools}
};
`;
}

/**
 * Minimal previews of the OpenAPI and MCP emitters. The CLI produces the real
 * artifacts; these exist so the shape is visible without installing anything.
 */
export function emitOpenapi(descriptor: SiteDescriptor): string {
  const schemes: Record<string, unknown> = {};
  const schemeNameFor = (auth: AuthMode): string | undefined => {
    if (auth.kind === "oAuth2") {
      const name = `oauth2_${auth.grant}`;
      schemes[name] = {
        type: "oauth2",
        flows: {
          [auth.grant]: {
            tokenUrl: auth.tokenUrl,
            scopes: Object.fromEntries((auth.scopes ?? []).map((s) => [s, s])),
          },
        },
      };
      return name;
    }
    if (auth.kind === "apiKey") {
      const name = `apiKey_${auth.location}_${auth.name.replace(/[^a-zA-Z0-9]/g, "_")}`;
      schemes[name] = { type: "apiKey", in: auth.location, name: auth.name };
      return name;
    }
    return undefined;
  };

  const paths: Record<string, unknown> = {};
  for (const op of descriptor.operations) {
    const endpoint = endpointFor(descriptor, op);
    const path = endpoint?.path.split("?")[0] ?? `/${op.commandPath.join("/")}`;
    const params = paramsFor(descriptor, op).map((p) => ({
      name: p.name,
      in: "query",
      required: false,
      schema: p.example
        ? { type: "string", example: p.example }
        : { type: "string" },
    }));

    const auth = resolveAuth(descriptor, op);
    let security: unknown;
    let extension: Record<string, unknown> = {};
    let authNote = "";
    if (auth) {
      if (auth.kind === "none") {
        security = [];
      } else if (auth.kind === "browserBootstrappedToken") {
        // OpenAPI has no scheme for "acquire via browser once, replay headless".
        // Declare it openly rather than fake an apiKey.
        extension = { "x-surfacer-auth": auth };
        authNote = " Needs: surfacer auth login.";
      } else {
        const name = schemeNameFor(auth);
        if (name) security = [{ [name]: [] }];
      }
    }

    paths[path] = {
      get: {
        operationId: op.commandPath.join("_"),
        summary: op.summary,
        description: op.description + authNote,
        tags: [op.commandPath[0] ?? "default"],
        ...(params.length > 0 ? { parameters: params } : {}),
        ...(security !== undefined ? { security } : {}),
        ...extension,
        responses: { default: { description: "Observed during recon" } },
        "x-surfacer-operation-kind": op.operationKind,
      },
    };
  }

  const hasSchemes = Object.keys(schemes).length > 0;
  return JSON.stringify(
    {
      openapi: "3.1.0",
      info: {
        title: descriptor.meta.displayName,
        version: descriptor.meta.irVersion,
      },
      servers: [{ url: new URL(descriptor.meta.sourceUrl).origin }],
      ...(hasSchemes ? { components: { securitySchemes: schemes } } : {}),
      paths,
    },
    null,
    2,
  );
}

export function emitMcp(descriptor: SiteDescriptor): string {
  const tools = descriptor.operations
    .map((op) => {
      const name = op.commandPath.join("_");
      const params = paramsFor(descriptor, op);
      const schema =
        params.length === 0
          ? "z.object({})"
          : `z.object({\n${params
              .map(
                (p) =>
                  `      ${p.name}: z.string().optional().describe("observed value: ${p.example ?? ""}"),`,
              )
              .join("\n")}\n    })`;
      const endpoint = endpointFor(descriptor, op);
      const path =
        endpoint?.path.split("?")[0] ?? `/${op.commandPath.join("/")}`;
      return `  server.registerTool(
    "${name}",
    {
      description: "${op.operationKind} on ${path}",
      inputSchema: ${schema},
      annotations: { readOnlyHint: ${op.operationKind === "read"} },
    },
    async (args) => call("${name}", "${op.operationKind}", "${path}", args),
  );`;
    })
    .join("\n\n");

  return `import { McpServer } from "@modelcontextprotocol/server";
import { serveStdio } from "@modelcontextprotocol/server/stdio";
import * as z from "zod/v4";

const ALLOWED_KINDS = new Set(["read"]);

serveStdio(() => {
  const server = new McpServer({ name: "${descriptor.meta.siteName}", version: "${descriptor.meta.irVersion}" });

${tools}

  return server;
});
`;
}

export const TARGETS = [
  { id: "help", label: "help", lang: "clihelp", emit: emitHelp },
  { id: "ts-cli", label: "ts-cli", lang: "typescript", emit: emitTsCli },
  { id: "mcp", label: "mcp", lang: "javascript", emit: emitMcp },
  { id: "openapi", label: "openapi", lang: "json", emit: emitOpenapi },
  {
    id: "just-bash",
    label: "just-bash",
    lang: "javascript",
    emit: emitJustBash,
  },
] as const;

export type TargetId = (typeof TARGETS)[number]["id"];
