use webctl_ir::{OperationKind, OperationTransport, SiteDescriptor};

pub fn emit_executor_config(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = &descriptor.meta.display_name;
    let source_url = &descriptor.meta.source_url;

    let mut tools = Vec::new();

    for op in &descriptor.operations {
        let cmd_name = op.command_path.join(".");
        let description = escape_js(&op.description);
        let op_kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let url = match &op.transport {
            OperationTransport::Http(http) => {
                if let Some(ref http_surface) = descriptor.http {
                    if let Some(endpoint) = http_surface.endpoints.get(http.endpoint_index) {
                        format!("{}{}", base_url(source_url), endpoint.path)
                    } else {
                        format!("{}/unknown", base_url(source_url))
                    }
                } else {
                    format!("{}/unknown", base_url(source_url))
                }
            }
            OperationTransport::Ax(_) => format!("ax://{site}/{cmd_name}"),
        };

        tools.push(format!(
            r#"    "{site}.{cmd_name}": {{
      description: "{description}",
      execute: async (args) => {{
        assertAllowed("{site}.{cmd_name}", "{op_kind}");
        const url = withQuery("{url}", args);
        const res = await fetch(url);
        return {{ status: res.status, url, body: await res.text() }};
      }},
    }}"#
        ));
    }

    let tools_str = tools.join(",\n");

    format!(
        r#"// Auto-generated by webctl emit just-bash
// Source: {source_url}
// Site: {site} ({display})
// Generated: {timestamp}
//
// Usage:
//   import {{ Bash }} from "just-bash";
//   import {{ createExecutor }} from "@just-bash/executor";
//   import {{ createWebctlExecutor }} from "./{site}.config.js";
//
//   const executor = await createWebctlExecutor(createExecutor);
//   const bash = new Bash({{
//     javascript: {{ invokeTool: executor.invokeTool }},
//     customCommands: executor.commands,
//   }});
//   await bash.exec("{site} --help");

/**
 * Operation kinds allowed to run without explicit opt-in.
 *
 * Inline tools bypass the executor's `onToolApproval` pipeline (the caller owns
 * `execute`), so the trust gate lives here instead.
 */
const ALLOWED_KINDS = new Set(["read"]);

function assertAllowed(path, operationKind) {{
  if (!ALLOWED_KINDS.has(operationKind)) {{
    throw new Error(
      `blocked: ${{path}} is a ${{operationKind}} operation. ` +
        `Add "${{operationKind}}" to ALLOWED_KINDS to permit it.`,
    );
  }}
}}

function withQuery(url, args) {{
  if (!args || typeof args !== "object") return url;
  const entries = Object.entries(args).filter(([, v]) => v !== undefined && v !== null);
  if (entries.length === 0) return url;
  const target = new URL(url);
  for (const [key, value] of entries) {{
    target.searchParams.set(key, String(value));
  }}
  return target.toString();
}}

export const webctlTools = {{
{tools_str}
}};

/**
 * Build an executor handle for this site.
 *
 * Takes `createExecutor` as a parameter so this file stays dependency-free and
 * inspectable; the caller supplies the implementation from
 * `@just-bash/executor`.
 */
export async function createWebctlExecutor(createExecutor, config = {{}}) {{
  return createExecutor({{ ...config, tools: {{ ...webctlTools, ...(config.tools ?? {{}}) }} }});
}}
"#,
        timestamp = generated_at(),
    )
}

fn escape_js(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', " ")
        .replace('\r', " ")
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.to_string())
}

fn generated_at() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("epoch {secs}")
}
