use webctl_ir::{OperationKind, OperationTransport, SiteDescriptor};

pub fn emit_executor_config(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = &descriptor.meta.display_name;
    let source_url = &descriptor.meta.source_url;

    let mut tools = Vec::new();

    for op in &descriptor.operations {
        let cmd_name = op.command_path.join(".");
        let description = escape_js(&op.description);
        let op_kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let endpoint = match &op.transport {
            OperationTransport::Http(http) => descriptor
                .http
                .as_ref()
                .and_then(|surface| surface.endpoints.get(http.endpoint_index)),
            OperationTransport::Ax(_) => None,
        };

        let url = match (&op.transport, endpoint) {
            // `path` still carries the recon-time query template
            // (`/user?id={id}`); parameters are supplied at call time, so only
            // the path portion belongs in the base URL.
            (OperationTransport::Http(_), Some(endpoint)) => format!(
                "{}{}",
                base_url(source_url),
                endpoint.path.split('?').next().unwrap_or(&endpoint.path)
            ),
            (OperationTransport::Http(_), None) => format!("{}/unknown", base_url(source_url)),
            (OperationTransport::Ax(_), _) => format!("ax://{site}/{cmd_name}"),
        };

        let params_doc = endpoint
            .map(|e| e.params.as_slice())
            .unwrap_or_default()
            .iter()
            .map(|p| {
                let example = p
                    .example
                    .as_deref()
                    .map(|v| format!(" (e.g. {})", escape_js(v)))
                    .unwrap_or_default();
                format!("      //   {}{}", escape_js(&p.name), example)
            })
            .collect::<Vec<_>>();

        let params_comment = if params_doc.is_empty() {
            String::new()
        } else {
            format!(
                "\n      // Parameters observed during recon:\n{}\n",
                params_doc.join("\n")
            )
        };

        tools.push(format!(
            r#"    "{site}.{cmd_name}": {{
      description: "{description}",{params_comment}
      execute: async (args) => {{
        assertAllowed("{site}.{cmd_name}", "{op_kind}");
        const url = withQuery("{url}", args);
        const res = await fetch(url);
        return {{ status: res.status, url, body: await res.text() }};
      }},
    }}"#
        ));
    }

    let tools_str = tools.join(",\n");

    format!(
        r#"// Auto-generated by webctl emit just-bash
// Source: {source_url}
// Site: {site} ({display})
// Generated: {timestamp}
//
// Usage:
//   import {{ Bash }} from "just-bash";
//   import {{ createExecutor }} from "@just-bash/executor";
//   import {{ createWebctlExecutor }} from "./{site}.config.js";
//
//   const executor = await createWebctlExecutor(createExecutor);
//   const bash = new Bash({{
//     javascript: {{ invokeTool: executor.invokeTool }},
//     customCommands: executor.commands,
//   }});
//   await bash.exec("{site} --help");

/**
 * Operation kinds allowed to run without explicit opt-in.
 *
 * Inline tools bypass the executor's `onToolApproval` pipeline (the caller owns
 * `execute`), so the trust gate lives here instead.
 */
const ALLOWED_KINDS = new Set(["read"]);

function assertAllowed(path, operationKind) {{
  if (!ALLOWED_KINDS.has(operationKind)) {{
    throw new Error(
      `blocked: ${{path}} is a ${{operationKind}} operation. ` +
        `Add "${{operationKind}}" to ALLOWED_KINDS to permit it.`,
    );
  }}
}}

function withQuery(url, args) {{
  if (!args || typeof args !== "object") return url;
  const entries = Object.entries(args).filter(([, v]) => v !== undefined && v !== null);
  if (entries.length === 0) return url;
  const target = new URL(url);
  for (const [key, value] of entries) {{
    target.searchParams.set(key, String(value));
  }}
  return target.toString();
}}

export const webctlTools = {{
{tools_str}
}};

/**
 * Build an executor handle for this site.
 *
 * Takes `createExecutor` as a parameter so this file stays dependency-free and
 * inspectable; the caller supplies the implementation from
 * `@just-bash/executor`.
 */
export async function createWebctlExecutor(createExecutor, config = {{}}) {{
  return createExecutor({{ ...config, tools: {{ ...webctlTools, ...(config.tools ?? {{}}) }} }});
}}
"#,
        timestamp = generated_at(),
    )
}

fn escape_js(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', " ")
        .replace('\r', " ")
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| format!("{}://{}", u.scheme(), u.host_str().unwrap_or("localhost")))
        .unwrap_or_else(|_| source_url.to_string())
}

fn generated_at() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    format!("epoch {secs}")
}
