use webctl_ir::{OperationKind, OperationTransport, ParamDescriptor, SiteDescriptor};

/// Emit a self-contained TypeScript CLI for a site.
///
/// Unlike the Rust shim, which shells out to `webctl exec`, this program
/// carries the whole descriptor inline and needs nothing else installed. It is
/// written to compile under `scriptc`, so it can ship as a native binary with
/// no runtime.
pub fn emit_ts_cli(descriptor: &SiteDescriptor) -> String {
    let site = &descriptor.meta.site_name;
    let display = escape_ts(&descriptor.meta.display_name);
    let source_url = &descriptor.meta.source_url;
    let base = base_url(source_url);

    let mut entries = Vec::new();

    for op in &descriptor.operations {
        let command = op.command_path.join(" ");
        let description = escape_ts(&op.description);
        let kind = match op.operation_kind {
            OperationKind::Read => "read",
            OperationKind::Write => "write",
            OperationKind::Other => "other",
        };

        let endpoint = match &op.transport {
            OperationTransport::Http(http) => descriptor
                .http
                .as_ref()
                .and_then(|surface| surface.endpoints.get(http.endpoint_index)),
            OperationTransport::Ax(_) => None,
        };

        let path = endpoint
            .map(|e| e.path.split('?').next().unwrap_or(&e.path).to_string())
            .unwrap_or_else(|| format!("/{}", op.command_path.join("/")));

        let params = endpoint.map(|e| e.params.as_slice()).unwrap_or_default();

        entries.push(format!(
            "  {{\n    name: {},\n    description: {},\n    kind: {},\n    path: {},\n    params: [{}],\n  }}",
            quote(&command),
            quote(&description),
            quote(kind),
            quote(&path),
            render_params(params),
        ));
    }

    let operations = entries.join(",\n");

    format!(
        r#"// Auto-generated by webctl emit ts-cli
// Source: {source_url}
// Site: {site} ({display})
//
// Build a native binary (no runtime required):
//   scriptc build {site}.ts --dynamic -o {site}
//
// `fetch` has no static lowering yet, so the network call runs in the
// embedded engine and `--dynamic` is required. Everything else compiles
// statically.

type OperationKind = "read" | "write" | "other";

interface Param {{
  name: string;
  example: string;
}}

interface Operation {{
  name: string;
  description: string;
  kind: OperationKind;
  path: string;
  params: Param[];
}}

const SITE = {site_lit};
const DISPLAY = {display_lit};
const BASE = {base_lit};

const OPERATIONS: Operation[] = [
{operations}
];

// Operation kinds allowed to run without an explicit opt-in. Recon cannot
// tell a harmless write from a destructive one, so writes stay blocked
// until a human widens this.
const ALLOWED_KINDS = new Set<string>(["read"]);

function findOperation(name: string): Operation | undefined {{
  for (const op of OPERATIONS) {{
    if (op.name === name) return op;
  }}
  return undefined;
}}

function pad(text: string, width: number): string {{
  let out = text;
  while (out.length < width) out = out + " ";
  return out;
}}

function buildHelp(): string {{
  let width = 0;
  for (const op of OPERATIONS) {{
    if (op.name.length > width) width = op.name.length;
  }}

  const lines: string[] = [];
  lines.push(SITE + " — " + DISPLAY);
  lines.push("");
  lines.push("USAGE");
  lines.push("  " + SITE + " <command> [key=value ...]");
  lines.push("");
  lines.push("COMMANDS");
  for (const op of OPERATIONS) {{
    lines.push("  " + pad(op.name, width) + "  " + op.description);
    if (op.params.length > 0) {{
      const flags: string[] = [];
      for (const p of op.params) {{
        flags.push(p.example.length > 0 ? p.name + "=" + p.example : p.name + "=");
      }}
      lines.push("  " + pad("", width) + "  " + flags.join(" "));
    }}
  }}
  lines.push("");
  lines.push("FLAGS");
  lines.push("  --json    Print the raw response body");
  lines.push("  --help    Show this help");
  return lines.join("\n");
}}

function parseArgs(argv: string[]): Map<string, string> {{
  const out = new Map<string, string>();
  for (const arg of argv) {{
    if (arg === "--json") continue;
    const eq = arg.indexOf("=");
    if (eq > 0) out.set(arg.slice(0, eq), arg.slice(eq + 1));
  }}
  return out;
}}

function encode(value: string): string {{
  return encodeURIComponent(value);
}}

function withQuery(url: string, args: Map<string, string>): string {{
  if (args.size === 0) return url;
  const parts: string[] = [];
  for (const [key, value] of args) {{
    parts.push(encode(key) + "=" + encode(value));
  }}
  return url + "?" + parts.join("&");
}}

async function run(argv: string[]): Promise<number> {{
  const command = argv.length > 0 ? argv[0] : "";

  if (command === "" || command === "--help" || command === "-h") {{
    console.log(buildHelp());
    return 0;
  }}

  const op = findOperation(command);
  if (op === undefined) {{
    console.error("unknown command: " + command);
    console.error("run `" + SITE + " --help` to list commands");
    return 127;
  }}

  if (!ALLOWED_KINDS.has(op.kind)) {{
    console.error(
      "blocked: " + op.name + " is a " + op.kind + " operation. " +
        "Edit ALLOWED_KINDS to permit it.",
    );
    return 77;
  }}

  let wantsJson = false;
  for (const arg of argv) {{
    if (arg === "--json") wantsJson = true;
  }}

  const args = parseArgs(argv.slice(1));
  const url = withQuery(BASE + op.path, args);

  const res = await fetch(url);
  const body = await res.text();

  if (wantsJson) {{
    console.log(body);
  }} else {{
    console.log(JSON.stringify({{ status: res.status, url: url, bytes: body.length }}));
  }}

  return res.status >= 200 && res.status < 300 ? 0 : 1;
}}

// scriptc rejects top-level await, so the entry point is an async function.
async function main(): Promise<void> {{
  const code = await run(process.argv.slice(2));
  process.exit(code);
}}

main();
"#,
        site_lit = quote(site),
        display_lit = quote(&display),
        base_lit = quote(&base),
    )
}

fn render_params(params: &[ParamDescriptor]) -> String {
    if params.is_empty() {
        return String::new();
    }
    let rendered = params
        .iter()
        .map(|p| {
            format!(
                "{{ name: {}, example: {} }}",
                quote(&escape_ts(&p.name)),
                quote(&escape_ts(p.example.as_deref().unwrap_or("")))
            )
        })
        .collect::<Vec<_>>()
        .join(", ");
    rendered
}

fn quote(value: &str) -> String {
    format!("\"{value}\"")
}

fn escape_ts(input: &str) -> String {
    input
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', " ")
        .replace('\r', " ")
}

fn base_url(source_url: &str) -> String {
    url::Url::parse(source_url)
        .map(|u| {
            format!(
                "{}://{}",
                u.scheme(),
                u.host_str().unwrap_or("localhost")
            )
        })
        .unwrap_or_else(|_| source_url.trim_end_matches('/').to_string())
}
